### ISSUE TITLE
libgstvideo-1.0.so.0: undefined reference to `c_RkRgaInit'

### ISSUE THREAD

**Issue by kalujee** [zhuyuliang/gst_rtsp_client#1]
使用老版本的linux-rga库没有问题，使用最新版本的[linux-rga库](https://github.com/lihuang1111/linux-rga)报这个错误。
如果不使用新版本的linux-rga库，wrapbuffer_virtualaddr这个方法又无法使用！麻烦老师看看可以怎么处理呀！谢谢了

**Comment by zhuyuliang** [comment]
不知道你用的是那个头文件库，是不是新版的需要初始化？
RockchipRga.h / im2d_api/im2d.hpp 调用的哪个头文件呢？

**Comment by zhuyuliang** [comment]
https://github.com/airockchip/librga的全新版本还没有适配，稍后重新适配下。

**Comment by zhensang** [comment]
![image](https://github.com/zhuyuliang/gst_rtsp_client/assets/142678204/fb13b710-a391-4b7f-b12a-6d9fb4acc03a)
请问我这个怎么无法连接，直接用playbin是可以的

**Comment by zhuyuliang** [comment]
已解决

**Comment by zhensang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
