### ISSUE TITLE
LightTrack的issue关了只能在这提问

### ISSUE THREAD

**Issue by fly-miao** [zhuyuliang/gst_rtsp_client#10]
您好，向您请教关于NanoTrack在RK3588平台的C++实现出现的问题。我参考NanoTrack原作者的C++代码和您使用lighttrack的代码写了使用rknn模型的代码，但是在解析输出的结果时出现问题：预测的目标框位置差距很大而且从第二帧开始预测框就不对了，想询问解决的办法！
NanoTrack跟LightTrack很相似，我的模型也是按照你的差不多结构设置的。

rknn_input zf_xf[2];
    memset(zf_xf, 0, sizeof(zf_xf));
    zf_xf[0].index = 0;
    zf_xf[0].size = zf[0].size;
    zf_xf[0].pass_through = 0;   
    zf_xf[0].type = RKNN_TENSOR_FLOAT32;
    zf_xf[0].fmt = RKNN_TENSOR_NHWC;
    zf_xf[0].buf = zf[0].buf;
 
    zf_xf[1].index = 1;
    zf_xf[1].size = xf[0].size;
    zf_xf[1].pass_through = 0;
    zf_xf[1].type = RKNN_TENSOR_FLOAT32;
    zf_xf[1].fmt = RKNN_TENSOR_NHWC;
    zf_xf[1].buf = xf[0].buf;
    
    rknn_inputs_set(net_head, 2, zf_xf);
 
    rknn_run(net_head, NULL);
 
    rknn_output outputs[2];
    memset(outputs, 0, sizeof(outputs));
    for (auto & output : outputs) {
        output.want_float = 1;
        output.is_prealloc = 0;
    }
    rknn_outputs_get(net_head, 2, outputs, NULL);
 
    std::vector<float> cls_score_sigmoid;
 
 
    float* cls_score_data = (float*)outputs[0].buf;
    //print_rknn(cls_score_data, "cls_score_rknn_cpp.txt");
    float* bbox_pred_data = (float*)outputs[1].buf;
    print_rknn(bbox_pred_data, "bbox_pred_rknn_cpp.txt");            
    /* debug */
 
    cls_score_sigmoid.clear();
 
    int cols = cfg.score_size;
    int rows = cfg.score_size;
 
    for (int i = 0; i < cols*rows; i++)   //16x16
    {        
        cls_score_sigmoid.push_back(sigmoid(cls_score_data[i]));
    }
 
    std::vector<float> pred_x1(cols*rows, 0), pred_y1(cols*rows, 0), pred_x2(cols*rows, 0), pred_y2(cols*rows, 0);
 
    float* bbox_pred_data1 = (float*)outputs[1].buf;
    float* bbox_pred_data2 = (float*)outputs[1].buf + cols*rows;
    float* bbox_pred_data3 = (float*)outputs[1].buf + 2*cols*rows;
    float* bbox_pred_data4 = (float*)outputs[1].buf + 3*cols*rows;
    
    for (int i=0; i<rows; i++)
    {
        for (int j=0; j<cols; j++)
        {
            pred_x1[i*cols + j] = this->grid_to_search_x[i*cols + j] - bbox_pred_data1[i*cols + j];
            pred_y1[i*cols + j] = this->grid_to_search_y[i*cols + j] - bbox_pred_data2[i*cols + j];
            pred_x2[i*cols + j] = this->grid_to_search_x[i*cols + j] + bbox_pred_data3[i*cols + j];
            pred_y2[i*cols + j] = this->grid_to_search_y[i*cols + j] + bbox_pred_data4[i*cols + j];
        }
    }

**Comment by zhuyuliang** [comment]
帧数据的buf是不是指针，共享内存的数据？，如果做一下内存拷贝在识别试试

**Comment by fly-miao** [comment]
感谢您的回复，帧数据的buf是指针，指向输出的结果，“如果做一下内存拷贝在识别试试”我不太理解这个，可以在我上面的代码中体现一下么

**Comment by fly-miao** [comment]
head输出格式是NCHW，两路输出其中reg输出是1*4*16*16；cls输出是1*2*16*16

**Comment by zhuyuliang** [comment]
指针就有可能在其他地方改变这个地址的内容，还有就是要注意模型支持的图片数据格式，是RGB还是BGR，如果错了也会到导致问题。

**Comment by fly-miao** [comment]
了解了，上面的格式问题已经确认过了，想请教一下怎么从1x4x16x16的输出中解析出预测的bbox，上面的
`float* bbox_pred_data1 = (float*)outputs[1].buf;
float* bbox_pred_data2 = (float*)outputs[1].buf + cols*rows;
float* bbox_pred_data3 = (float*)outputs[1].buf + 2*cols*rows;
float* bbox_pred_data4 = (float*)outputs[1].buf + 3*cols*rows`
是什么原理呢

**Comment by zhuyuliang** [comment]
这个超纲了，这个具体还要参考LightTrack的python项目的解的方法去写，因为模型输出的数据格式是一致的。

**Comment by fly-miao** [comment]
好的，谢谢答复
