### ISSUE TITLE
代码编译跑通没问题，但是我保存的RTSP流的图片是乱码

### ISSUE THREAD

**Issue by a514154639** [zhuyuliang/gst_rtsp_client#4]
![image](https://user-images.githubusercontent.com/39019284/221767799-4b744f15-85dd-46ae-8ec6-a5280d509868.png)
![image](https://user-images.githubusercontent.com/39019284/221767879-de0f9fa6-a6f6-42d0-8387-cdaf59f76764.png)
我的环境是NX Jetpack4.6.2

**Comment by zhuyuliang** [comment]
mpp frame size : 1008 明显是有问题的
NX Jetpack不要使用gstreamer-rockchip-extra插件
应该使用deepstream的Gst-nvvideo4linux2插件进行硬解码

**Comment by a514154639** [comment]
> 
是直接把decode插件改成deepstream的nvv4l2decoder吗

**Comment by zhuyuliang** [comment]
不用改，decodebin会自动调取你的nvv4l2decoder插件
你要把mpp的插件删除

**Comment by a514154639** [comment]
![image](https://user-images.githubusercontent.com/39019284/221830049-0f6198e2-3292-49d0-a629-ec2201afaa54.png)
pipeline里面没有mpp插件 我只用到了read_Opencv的接口  没有用read_Rga pipeline里面还需要删什么吗？之前没接触过mpp 我去您的streamer-rockchip-extra仓库看了一下 也没有那几个element

**Comment by zhuyuliang** [comment]
read_Opencv接口没问题，目前的问题是在解码的时候出的问题，你可以查看下Gstreamer你本地是否有nvv4l2decoder这个插件用gst-inspect-1.0指令

**Comment by a514154639** [comment]
本地上是有nvv4l2decoder这个插件的，并且调用RTSP摄像头的时候nx的jtop上面可以看到NVDEC是打开的，不过我在用其他简单demo测试的时候NVDEC的频率是波动的，用您的代码调用的时候频率一直是满的，不知道是不是这个原因，解码的问题代码其他地方还有需要修改的地方吗？

**Comment by zhuyuliang** [comment]
你把1225行的 // g_print("mpp frame size : %d \n", map_info.size);的注释打开，看一下，size后面的帧输出多少，如果NVDEC被利用起来了，那么说明gstreamer的部分没问题，gstreamer是通用的管道模式，基本不用修改的。解码插件是通过decodebin自动调用的。

**Comment by zhuyuliang** [comment]
如果解码正常，那要修改read_Opencv转换的代码，因为mpp是16位对齐，所以得到的buffer要做转换，从1238行开始你要针对NVDEC解出来的buffer进行内存拷贝和转换进行修改。

**Comment by a514154639** [comment]
![image](https://user-images.githubusercontent.com/39019284/222020546-405e4a0f-a921-4732-8a38-4c544abf491a.png)
后面帧输出还是1008，没有变化

**Comment by a514154639** [comment]
![image](https://user-images.githubusercontent.com/39019284/222021532-23046ce1-39ff-4c95-b0b0-3ddcbe5fd10b.png)
我用这个demo跑出来的map.size大小是6220800，我有一个疑问，在您的代码中获得buffer的方式不是没有用到mpp吗？为什么还需要进行转换
![image](https://user-images.githubusercontent.com/39019284/222022343-282404bf-4c09-4608-9b4e-54afa5bedaf0.png)

**Comment by zhuyuliang** [comment]
目测你上面的代码集成了nvvideoconvert这个插件吧，因为我read_opencv拿到的是yuv的图片需要转换的，稍后我这边新开分支支持下，好了我通知你。

**Comment by a514154639** [comment]
是的确实集成了nvvideoconvert这个插件，我尝试在您的代码中添加但是没有成功，这个问题麻烦您了，感谢

**Comment by zhuyuliang** [comment]
@a514154639 你demo能给我个链接吗？

**Comment by a514154639** [comment]
> @a514154639 你demo能给我个链接吗？

@zhuyuliang [https://github.com/a514154639/rtsp_demo](url)

**Comment by zhuyuliang** [comment]
@a514154639 问题已处理，可以移到https://github.com/zhuyuliang/gst_rtsp_client/tree/jetpacklib这个分支
