### ISSUE TITLE
调用RTSP相机没问题，但是收到的图片有损坏

### ISSUE THREAD

**Issue by a514154639** [zhuyuliang/gst_rtsp_client#7]
![image](https://user-images.githubusercontent.com/39019284/223356095-04fe5bd5-1d19-4979-a408-3feab45390a8.png)
![image](https://user-images.githubusercontent.com/39019284/223356211-fedef55d-a9c8-4e11-ba15-84d44bf808a0.png)
![image](https://user-images.githubusercontent.com/39019284/223356278-9d2bdcaf-38db-4e6e-8c11-40d7f6f4e752.png)
相机本身链接也没问题

**Comment by zhuyuliang** [comment]
gst-launch-1.0 uridecodebin uri=rtsp://admin:admin@192.168.2.29:554 ! nvvidconv ! 'video/x-raw(memory:NVMM), format=RGBA' ! nvoverlaysink -e
用这个指令试一下看看显示是否正常

**Comment by a514154639** [comment]
![image](https://user-images.githubusercontent.com/39019284/223399733-90e42891-bd14-4d88-bafd-de02d79f4b1c.png)
我在另一台nx上测试没问题，但是两台机器decodebin中插件是不一样的，不知道是不是这个原因

**Comment by a514154639** [comment]
> gst-launch-1.0 uridecodebin uri=rtsp://admin:admin@192.168.2.29:554 ! nvvidconv ! 'video/x-raw(memory:NVMM), format=RGBA' ! nvoverlaysink -e 用这个指令试一下看看显示是否正常

用我之前的那个demo也是可以的，
<img width="274" alt="ec05257431778d1b5553563c3ce631f" src="https://user-images.githubusercontent.com/39019284/223401008-bf8825ca-1b82-4fef-8a73-a2b9369fb352.png">
两台nx的HW engines参数有些不同

**Comment by a514154639** [comment]
> ![image](https://user-images.githubusercontent.com/39019284/223399733-90e42891-bd14-4d88-bafd-de02d79f4b1c.png) 我在另一台nx上测试没问题，但是两台机器decodebin中插件是不一样的，不知道是不是这个原因

少的这几个插件gstreamer中都是有的

**Comment by zhuyuliang** [comment]
重新安装下gstreamer试试，我用的jetpack4.6.2和deepstream6.0.1，不知道这些版本对插件是否有影响。
