### ISSUE TITLE
执行multip_thread_rtsp.py，执行报错，是插件没安装好？

### ISSUE THREAD

**Issue by eyu11** [zhuyuliang/gst_rtsp_client#9]
1、执行multip_thread_rtsp.py，报的错
![image](https://user-images.githubusercontent.com/61813449/224933714-cb26401c-7e73-4454-bfc4-331d71fa5676.png)

2、执行multip_thread_rtsp.py，报的错
rtspclient.mread这个方法不存在？直接用gst_rtsp_client_api.pypyapi/mread_rga？
![image](https://user-images.githubusercontent.com/61813449/224934013-861f8054-2fa2-4ddc-adc3-990ad77538b6.png)

**Comment by zhuyuliang** [comment]
你是自己编过了测试的，还是用工程里的so包？如果没有rga配置，可以用opencv的调用方法试试。
<img width="537" alt="image" src="https://user-images.githubusercontent.com/7247737/225176460-a813daa9-5b16-434f-8ca7-b1c41c031d33.png">
感觉你的mpp库安装也有问题

**Comment by eyu11** [comment]
直接用你编译好的包，那个报错好像不影响~~ 我直接用 gstreamer 命令是可以实现编解码

**Comment by zhuyuliang** [comment]
需要你重新编译才行，根据你机器系统配置去编译
